var laavor_Puzzle_monomino;var laavor_Puzzle_domino;var laavor_Puzzle_tromino;function LaavorExpander(laavor_Puzzle_tetromino,laavor_Puzzle_pentomino){laavor_Puzzle_monomino=[];if(laavor_Puzzle_domino===undefined||laavor_Puzzle_domino===null)
{laavor_Puzzle_domino=[];}
laavor_Puzzle_domino.push(laavor_Puzzle_tetromino);if(laavor_Puzzle_tromino===undefined||laavor_Puzzle_tromino===null)
{laavor_Puzzle_tromino=[];}
if(laavor_Puzzle_pentomino!==undefined&&laavor_Puzzle_pentomino!==null){laavor_Puzzle_tromino[laavor_Puzzle_tetromino]=laavor_Puzzle_pentomino;}
else{laavor_Puzzle_tromino[laavor_Puzzle_tetromino]=GetDefaults()}}
window.addEventListener('load',function(){var _7_7_=laavor_Puzzle_domino.length;for(var _10_9_8_7=0;_10_9_8_7<_7_7_;_10_9_8_7++)
{laavor_Puzzle_heptomino(laavor_Puzzle_domino[_10_9_8_7]);}});function laavor_Puzzle_heptomino(laavor_Puzzle_1){var laavor_Puzzle_Polyomino=document.getElementById(laavor_Puzzle_1);if(laavor_Puzzle_Polyomino!==undefined&&laavor_Puzzle_Polyomino!==null){var laavor_Puzzle_octomino=laavor_Puzzle_Polyomino.children;laavor_Puzzle_dominos__(laavor_Puzzle_tromino[laavor_Puzzle_1]);var laavor_Puzzle_2=laavor_Puzzle_tromino[laavor_Puzzle_1];var laavor_Puzzle_nonomino=elemSpace=document.createElement("span");;var laavor_Puzzle_decomino=elemSpace=document.createElement("span");;var laavor_Puzzle_Song_dynasty__;if(laavor_Puzzle_2.imageArrowExpanded!=="none"&&laavor_Puzzle_2.imageArrowClosed!=="none")
{laavor_Puzzle_Song_dynasty__=document.createElement("img");if(laavor_Puzzle_2.startExpanded.toString()==="true"){laavor_Puzzle_Song_dynasty__.src=laavor_Puzzle_2.imageArrowExpanded;}
else{laavor_Puzzle_Song_dynasty__.src=laavor_Puzzle_2.imageArrowClosed;}
laavor_Puzzle_Song_dynasty__.style.width=laavor_Puzzle_2.imageArrowWidth.replace("px","")+"px";laavor_Puzzle_Song_dynasty__.style.height=laavor_Puzzle_2.imageArrowHeight.replace("px","")+"px";laavor_Puzzle_Song_dynasty__.style.verticalAlign="baseline";laavor_Puzzle_nonomino.innerHTML="&nbsp&nbsp&nbsp";laavor_Puzzle_decomino.innerHTML="&nbsp&nbsp&nbsp";}
else if((laavor_Puzzle_2.imageArrowExpanded!=="none"&&laavor_Puzzle_2.imageArrowClosed==="none")||(laavor_Puzzle_2.imageArrowExpanded==="none"&&laavor_Puzzle_2.imageArrowClosed!=="none")){throw new Error("When used imageArrowExpanded it is also necessary to use the imageArrowClosed property or vice versa, or leave empty.");}
else{laavor_Puzzle_Song_dynasty__=document.createElement("span");laavor_Puzzle_Song_dynasty__.innerHTML="";laavor_Puzzle_nonomino.innerHTML="";laavor_Puzzle_decomino.innerHTML="";}
try
{var laavor_Puzzle_Wulin=document.createElement("span");laavor_Puzzle_Wulin.innerHTML=laavor_Puzzle_octomino[0].innerHTML;laavor_Puzzle_octomino[0].innerHTML="";laavor_Puzzle_octomino[0].appendChild(laavor_Puzzle_decomino);laavor_Puzzle_octomino[0].appendChild(laavor_Puzzle_Song_dynasty__);laavor_Puzzle_octomino[0].appendChild(laavor_Puzzle_nonomino);laavor_Puzzle_octomino[0].appendChild(laavor_Puzzle_Wulin);}
catch(e){throw new Error("Error while mounting title, if necessary contact Laavor support.");}
try{var laavor_Puzzle_Zhou_Mi=laavor_Puzzle_1232(laavor_Puzzle_octomino[1]);var laavor_Puzzle_28_tiles={laavor_Puzzle_player_Scoring_game:laavor_Puzzle_octomino[0],laavor_Puzzle_1298:laavor_Puzzle_Song_dynasty__,laavor_Puzzle_player_Draw_game:laavor_Puzzle_octomino[1],laavor_Puzzle_Blocking_game:laavor_Puzzle_Zhou_Mi};laavor_Puzzle_octomino[1].style.display='none';laavor_Puzzle_monomino[laavor_Puzzle_1]=laavor_Puzzle_28_tiles;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.setAttribute("_8_ball",laavor_Puzzle_1);laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.onclick=laavor_Puzzle_double_six;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.setAttribute("LaavorIsSelected",false);laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.backgroundColor=laavor_Puzzle_tromino[laavor_Puzzle_1].backgroundColorTitle;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.border="solid 1px";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.borderColor=laavor_Puzzle_tromino[laavor_Puzzle_1].borderColorTitle;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.color=laavor_Puzzle_tromino[laavor_Puzzle_1].textColorTitle;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.fontSize=laavor_Puzzle_tromino[laavor_Puzzle_1].fontSizeTitle.replace("em","")+'em';laavor_Puzzle_28_tiles.laavor_Puzzle_player_Draw_game.style.border="solid 1px";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Draw_game.style.borderColor=laavor_Puzzle_tromino[laavor_Puzzle_1].borderColorContent;laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.cursor="pointer";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.marginBottom="0px";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Draw_game.style.marginBottom="0px";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Scoring_game.style.marginTop="0px";laavor_Puzzle_28_tiles.laavor_Puzzle_player_Draw_game.style.marginTop="0x";if(laavor_Puzzle_tromino[laavor_Puzzle_1].startExpanded.toString()==="true"){laavor_Puzzle_monomino[laavor_Puzzle_1].laavor_Puzzle_player_Scoring_game.setAttribute("LaavorIsSelected",true);laavor_Puzzle_player_draws_seven_tiles(laavor_Puzzle_monomino[laavor_Puzzle_1]);}}
catch(e){throw new Error("The Title and Content order can not be interrupted, if necessary contact Laavor support.");}}
else{throw new Error("Item with idFather informed was not found.");}}
function laavor_Puzzle_dominos__(laavor_Puzzle_Line_of_play){var laavor_Puzzle_Scoring=laavor_Puzzle_hexomino();if(laavor_Puzzle_Line_of_play.startExpanded===undefined||laavor_Puzzle_Line_of_play.startExpanded===null){laavor_Puzzle_Line_of_play.startExpanded=laavor_Puzzle_Scoring.startExpanded;}
if(laavor_Puzzle_Line_of_play.backgroundColorTitle===undefined||laavor_Puzzle_Line_of_play.backgroundColorTitle===null){laavor_Puzzle_Line_of_play.backgroundColorTitle=laavor_Puzzle_Scoring.backgroundColorTitle;}
if(laavor_Puzzle_Line_of_play.borderColorTitle===undefined||laavor_Puzzle_Line_of_play.borderColorTitle===null){laavor_Puzzle_Line_of_play.borderColorTitle=laavor_Puzzle_Scoring.borderColorTitle;}
if(laavor_Puzzle_Line_of_play.textColorTitle===undefined||laavor_Puzzle_Line_of_play.textColorTitle===null){laavor_Puzzle_Line_of_play.textColorTitle=laavor_Puzzle_Scoring.textColorTitle;}
if(laavor_Puzzle_Line_of_play.fontSizeTitle===undefined||laavor_Puzzle_Line_of_play.fontSizeTitle===null){laavor_Puzzle_Line_of_play.fontSizeTitle=laavor_Puzzle_Scoring.fontSizeTitle;}
if(laavor_Puzzle_Line_of_play.borderColorContent===undefined||laavor_Puzzle_Line_of_play.borderColorContent===null){laavor_Puzzle_Line_of_play.borderColorContent=laavor_Puzzle_Scoring.borderColorContent;}
if(laavor_Puzzle_Line_of_play.imageArrowExpanded===undefined||laavor_Puzzle_Line_of_play.imageArrowExpanded===null){laavor_Puzzle_Line_of_play.imageArrowExpanded=laavor_Puzzle_Scoring.imageArrowExpanded;}
if(laavor_Puzzle_Line_of_play.imageArrowClosed===undefined||laavor_Puzzle_Line_of_play.imageArrowClosed===null){laavor_Puzzle_Line_of_play.imageArrowClosed=laavor_Puzzle_Scoring.imageArrowClosed;}
if(laavor_Puzzle_Line_of_play.imageArrowWidth===undefined||laavor_Puzzle_Line_of_play.imageArrowWidth===null){laavor_Puzzle_Line_of_play.imageArrowWidth=laavor_Puzzle_Scoring.imageArrowWidth;}
if(laavor_Puzzle_Line_of_play.imageArrowHeight===undefined||laavor_Puzzle_Line_of_play.imageArrowHeight===null){laavor_Puzzle_Line_of_play.imageArrowHeight=laavor_Puzzle_Scoring.imageArrowHeight;}}
function laavor_Puzzle_double_six(){try{var laavor_Puzzle_150_points=this.getAttribute("LaavorIsSelected");var _ul_li_ontem=this.getAttribute("_8_ball");var laavor_Puzzle_double_five=laavor_Puzzle_monomino[_ul_li_ontem];if(laavor_Puzzle_double_five!==undefined&&laavor_Puzzle_double_five!==null){if(laavor_Puzzle_150_points.toString()==='true'){laavor_Puzzle_double_four(laavor_Puzzle_double_five);}
else{laavor_Puzzle_player_draws_seven_tiles(laavor_Puzzle_double_five);}}
else{throw new Error("Error in count inside Expander(Click) contact Laavor.com with example.");}}
catch(e){throw new Error("Error in count inside Expander(Click) contact Laavor.com with example.");}}
String.prototype.res_is_42=function(){"use strict";var _7_7_=parseInt(this);return _7_7_;};function laavor_Puzzle_1232(laavor_Puzzle_six_five){if(laavor_Puzzle_six_five.clientHeight!==undefined&&laavor_Puzzle_six_five.clientHeight!==null){return laavor_Puzzle_six_five.clientHeight.toString().res_is_42();}
if(laavor_Puzzle_six_five.height!==undefined&&laavor_Puzzle_six_five.style.height!==null){return laavor_Puzzle_six_five.height.toString().res_is_42();}
if(laavor_Puzzle_six_five.offsetHeight!==undefined&&laavor_Puzzle_six_five.offsetHeight!==null){return laavor_Puzzle_six_five.offsetHeight.toString().res_is_42()-2;}
else{throw new Error("Error in count inside Expander(Height Item) contact Laavor.com with example.");}}
function changeHeightInTime(laavor_Puzzle_six_four,laavor_Puzzle_Bogus_play,laavor_Puzzle_Card_games){setTimeout(function(){laavor_Puzzle_six_four.style.height=laavor_Puzzle_Bogus_play.toString().replace("px","")+'px';},laavor_Puzzle_Card_games);}
function laavor_Puzzle_double_four(laavor_Puzzle_Texas_is_42){if(laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game!==undefined&&laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game!==null&&laavor_Puzzle_Texas_is_42.laavor_Puzzle_Blocking_game!==undefined&&laavor_Puzzle_Texas_is_42.laavor_Puzzle_Blocking_game!==null){var stepAnimation=laavor_Puzzle_Texas_is_42.laavor_Puzzle_Blocking_game/10;var laavor_Puzzle_Longest_domino_spiral=0;var laavor_Puzzle_Highest_domino_climb=50;laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game.style.opacity="0";for(var laavor_Puzzle_Longest_domino_wall__=laavor_Puzzle_Texas_is_42.laavor_Puzzle_Blocking_game;laavor_Puzzle_Longest_domino_wall__>0;laavor_Puzzle_Longest_domino_wall__-=stepAnimation){changeHeightInTime(laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game,laavor_Puzzle_Longest_domino_wall__,laavor_Puzzle_Highest_domino_climb);if(laavor_Puzzle_Longest_domino_spiral>11){throw new Error("Error in count inside Expander(Hide Item) contact Laavor.com with example.");}
laavor_Puzzle_Highest_domino_climb+=50;}
setTimeout(function(){laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game.style.height='0px';},laavor_Puzzle_Highest_domino_climb);laavor_Puzzle_Highest_domino_climb+=50;setTimeout(function(){laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game.style.display='none';},laavor_Puzzle_Highest_domino_climb);laavor_Puzzle_Highest_domino_climb+=50;setTimeout(function(){laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Draw_game.style.height=laavor_Puzzle_Texas_is_42.laavor_Puzzle_Blocking_game.toString()+'px';},laavor_Puzzle_Highest_domino_climb);laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Scoring_game.setAttribute("LaavorIsSelected",false);var _82_7=laavor_Puzzle_Texas_is_42.laavor_Puzzle_player_Scoring_game.getAttribute("_8_ball");if(laavor_Puzzle_tromino[_82_7].imageArrowExpanded!=="none"&&laavor_Puzzle_tromino[_82_7].imageArrowClosed!=="none")
{laavor_Puzzle_Texas_is_42.laavor_Puzzle_1298.src=laavor_Puzzle_tromino[_82_7].imageArrowClosed;}}}
function laavor_Puzzle_player_draws_seven_tiles(laavor_Puzzle_seven_tricks_equals_42_points){if(laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game!==undefined&&laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game!==null&&laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_Blocking_game!==undefined&&laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_Blocking_game!==null){var stepAnimation=laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_Blocking_game/10;var laavor_Puzzle_Largest_domino_tile=0;var laavor_Puzzle_Smallest_domino_tile=50;laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game.style.height=stepAnimation.toString()+'px';laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game.style.display='block';for(var laavor_Puzzle_Largest_domino_structure=stepAnimation;laavor_Puzzle_Largest_domino_structure<=laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_Blocking_game;laavor_Puzzle_Largest_domino_structure+=stepAnimation){changeHeightInTime(laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game,laavor_Puzzle_Largest_domino_structure,laavor_Puzzle_Smallest_domino_tile);if(laavor_Puzzle_Largest_domino_tile>11){throw new Error("Error in count inside Expander(Hide Item) contact Laavor.com with example.");}
laavor_Puzzle_Smallest_domino_tile+=50;}
setTimeout(function(){laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game.style.height=laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_Blocking_game.toString()+'px';laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Draw_game.style.opacity="1";},laavor_Puzzle_Smallest_domino_tile);laavor_Puzzle_Smallest_domino_tile+=50;laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Scoring_game.setAttribute("LaavorIsSelected",true);var _23_=laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_player_Scoring_game.getAttribute("_8_ball");if(laavor_Puzzle_tromino[_23_].imageArrowExpanded!=="none"&&laavor_Puzzle_tromino[_23_].imageArrowClosed!=="none")
{laavor_Puzzle_seven_tricks_equals_42_points.laavor_Puzzle_1298.src=laavor_Puzzle_tromino[_23_].imageArrowExpanded;}}}
function laavor_Puzzle_hexomino(){return{startExpanded:true,backgroundColorTitle:"black",borderColorTitle:"black",textColorTitle:"white",fontSizeTitle:"2em",borderColorContent:"black",imageArrowExpanded:"none",imageArrowClosed:"none",imageArrowWidth:"24px",imageArrowHeight:"24px"};}